# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Praxidi: Making teams better"
email: kit@transneptune.net
description: > # this means to ignore newlines until "baseurl:"
  We design immersive educational experiences that feel like games. No
  lectures. No slideshows. Your team will learn strategy and communication by
  taking chances, seeing what works, and fixing mistakes. At Praxidi, we
  believe that learning is always about doing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.praxidi.com"
enforce_ssl: "www.praxidi.com"

# Blog settings
permalink: "/blog/:year/:month/:day/:title/"

# Build settings
markdown: kramdown
